wersja = '1.0.9'
data_aktualizacji = "2025-05-16, 19:45:10"
run: bool = None
lokalizacja: str = None
clock = None
ustawienia: dict = None
jezyk: dict = None
window = None
Locations = None
mouse_x: int = None
mouse_y: int = None
mouse_pressed: list = None
mouse_scroll: int = None
pressed_keys: list = None
TextInput: list = None